"""
Write-back helpers: update sprint markdown files and sprint-status.yaml.
"""
from __future__ import annotations

import re
import yaml
from datetime import datetime
from pathlib import Path
from typing import Optional


# ── Path helpers ──────────────────────────────────────────────────────────────

def _sprint_path(studio_path: Path, sprint_n: int) -> Path:
    return studio_path / "production" / "sprints" / f"sprint-{sprint_n}.md"


def _status_yaml_path(studio_path: Path) -> Path:
    return studio_path / "production" / "sprint-status.yaml"


def _milestone_path(studio_path: Path, slug: str) -> Path:
    return studio_path / "production" / "milestones" / f"{slug}.md"


# ── sprint-status.yaml ────────────────────────────────────────────────────────

def load_status_yaml(studio_path: Path) -> dict:
    p = _status_yaml_path(studio_path)
    if not p.exists():
        return {"stories": []}
    try:
        data = yaml.safe_load(p.read_text(encoding='utf-8'))
        return data if isinstance(data, dict) else {"stories": []}
    except Exception:
        return {"stories": []}


def save_status_yaml(studio_path: Path, data: dict) -> None:
    p = _status_yaml_path(studio_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "# Auto-generated by nytwatch project management.\n"
        "# DO NOT edit manually — use /story-done to update story status.\n\n"
    )
    p.write_text(header + yaml.dump(data, default_flow_style=False, allow_unicode=True), encoding='utf-8')


def update_task_status(studio_path: Path, task_id: str, new_status: str, blocker: str = "") -> bool:
    """Set the status (and optionally blocker) for a task in sprint-status.yaml."""
    data = load_status_yaml(studio_path)
    for story in data.get('stories', []):
        if story.get('id') == task_id:
            story['status'] = new_status
            story['blocker'] = blocker
            if new_status == 'done' and not story.get('completed'):
                story['completed'] = datetime.now().strftime('%Y-%m-%d')
            elif new_status != 'done':
                story['completed'] = ''
            save_status_yaml(studio_path, data)
            return True
    return False


def upsert_task_in_yaml(studio_path: Path, sprint_n: int, task: dict) -> None:
    """Add or update a task entry in sprint-status.yaml."""
    data = load_status_yaml(studio_path)
    stories = data.setdefault('stories', [])
    for i, s in enumerate(stories):
        if s.get('id') == task['id']:
            stories[i] = {**s, **task}
            save_status_yaml(studio_path, data)
            return
    stories.append(task)
    save_status_yaml(studio_path, data)


def remove_task_from_yaml(studio_path: Path, task_id: str) -> None:
    data = load_status_yaml(studio_path)
    data['stories'] = [s for s in data.get('stories', []) if s.get('id') != task_id]
    save_status_yaml(studio_path, data)


def move_task_sprint_in_yaml(studio_path: Path, task_id: str, new_sprint: int) -> None:
    """Update sprint number for a task in sprint-status.yaml (if sprint field is stored)."""
    data = load_status_yaml(studio_path)
    for story in data.get('stories', []):
        if story.get('id') == task_id:
            story['sprint'] = new_sprint
            save_status_yaml(studio_path, data)
            return


# ── Sprint markdown files ─────────────────────────────────────────────────────

_SPRINT_TEMPLATE = """\
# Sprint {n} -- {start} to {end}

## Sprint Goal
{goal}

## Capacity
- Total days: 10
- Buffer (20%): 2 days reserved for unplanned work
- Available: 8 days

## Tasks

### Must Have (Critical Path)
| ID | Task | Agent/Owner | Est. Days | Dependencies | Acceptance Criteria |
|----|------|-------------|-----------|-------------|-------------------|

### Should Have
| ID | Task | Agent/Owner | Est. Days | Dependencies | Acceptance Criteria |
|----|------|-------------|-----------|-------------|-------------------|

### Nice to Have
| ID | Task | Agent/Owner | Est. Days | Dependencies | Acceptance Criteria |
|----|------|-------------|-----------|-------------|-------------------|

## Risks
| Risk | Probability | Impact | Mitigation |
|------|------------|--------|------------|

## Definition of Done for this Sprint
- [ ] All Must Have tasks completed
- [ ] All tasks pass acceptance criteria
- [ ] No S1 or S2 bugs in delivered features
"""


def create_sprint_file(studio_path: Path, sprint_n: int, goal: str, start_date: str, end_date: str) -> Path:
    p = _sprint_path(studio_path, sprint_n)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(_SPRINT_TEMPLATE.format(n=sprint_n, start=start_date, end=end_date, goal=goal), encoding='utf-8')
    return p


def update_sprint_metadata(studio_path: Path, sprint_n: int, goal: str, start_date: str, end_date: str) -> bool:
    p = _sprint_path(studio_path, sprint_n)
    if not p.exists():
        return False
    content = p.read_text(encoding='utf-8')

    # Update title line
    content = re.sub(
        r'^(# Sprint \d+\s*)[-–—]+\s*.*$',
        f'# Sprint {sprint_n} -- {start_date} to {end_date}',
        content, flags=re.MULTILINE, count=1,
    )

    # Update goal section body
    content = re.sub(
        r'(## Sprint Goal\s*\n).*?(?=\n## |\Z)',
        f'\\g<1>{goal}\n\n',
        content, flags=re.DOTALL, count=1,
    )

    p.write_text(content, encoding='utf-8')
    return True


def delete_sprint_file(studio_path: Path, sprint_n: int) -> bool:
    p = _sprint_path(studio_path, sprint_n)
    if p.exists():
        p.unlink()
        return True
    return False


def _make_row(task: dict) -> str:
    """Build a markdown table row string for the given task dict."""
    tid    = task.get('id', '')
    name   = task.get('name', '')
    owner  = task.get('owner', '')
    est    = str(task.get('estimate_days', 0))
    deps   = task.get('dependencies', '')
    ac     = task.get('acceptance_criteria', '')
    return f"| {tid} | {name} | {owner} | {est} | {deps} | {ac} |"


_SECTION_HEADERS = {
    "must-have":    "### Must Have (Critical Path)",
    "should-have":  "### Should Have",
    "nice-to-have": "### Nice to Have",
}

_TABLE_HEADER = "| ID | Task | Agent/Owner | Est. Days | Dependencies | Acceptance Criteria |"
_TABLE_SEP    = "|----|------|-------------|-----------|-------------|-------------------|"


def add_task_to_sprint(studio_path: Path, sprint_n: int, task: dict) -> bool:
    p = _sprint_path(studio_path, sprint_n)
    if not p.exists():
        return False

    content = p.read_text(encoding='utf-8')
    priority = task.get('priority', 'should-have')
    header = _SECTION_HEADERS.get(priority, _SECTION_HEADERS["should-have"])
    row = _make_row(task)

    # Find the section's table separator row and append after the last data row
    # Pattern: header line ... table sep line ... (existing rows) ... (next ## or ###)
    pattern = rf'({re.escape(header)}.*?{re.escape(_TABLE_SEP)}\n)(.*?)(?=\n###|\n##|\Z)'

    def _inserter(m: re.Match) -> str:
        table_top = m.group(1)
        table_body = m.group(2).rstrip('\n')
        return f"{table_top}{table_body}\n{row}\n"

    new_content, n = re.subn(pattern, _inserter, content, count=1, flags=re.DOTALL)

    if n == 0:
        # Section not found – append row to end of file
        new_content = content.rstrip('\n') + f"\n{row}\n"

    p.write_text(new_content, encoding='utf-8')
    return True


def remove_task_from_sprint(studio_path: Path, sprint_n: int, task_id: str) -> bool:
    p = _sprint_path(studio_path, sprint_n)
    if not p.exists():
        return False
    content = p.read_text(encoding='utf-8')
    new_content = re.sub(
        rf'^\|\s*{re.escape(task_id)}\s*\|[^\n]*\n?', '', content, flags=re.MULTILINE
    )
    if new_content != content:
        p.write_text(new_content, encoding='utf-8')
        return True
    return False


def update_task_in_sprint(studio_path: Path, sprint_n: int, task: dict) -> bool:
    """Replace the markdown row for task['id'] in the sprint file."""
    p = _sprint_path(studio_path, sprint_n)
    if not p.exists():
        return False
    content = p.read_text(encoding='utf-8')
    task_id = task['id']
    new_row = _make_row(task)
    new_content = re.sub(
        rf'^\|\s*{re.escape(task_id)}\s*\|[^\n]*',
        new_row,
        content, flags=re.MULTILINE, count=1,
    )
    if new_content != content:
        p.write_text(new_content, encoding='utf-8')
        return True
    return False


def move_task_between_sprints(
    studio_path: Path,
    task: dict,
    from_sprint: int,
    to_sprint: int,
) -> bool:
    """Remove task row from source sprint file and add to destination sprint file."""
    remove_task_from_sprint(studio_path, from_sprint, task['id'])
    task_copy = dict(task, sprint=to_sprint)
    add_task_to_sprint(studio_path, to_sprint, task_copy)
    move_task_sprint_in_yaml(studio_path, task['id'], to_sprint)
    return True


# ── Milestones ────────────────────────────────────────────────────────────────

_MILESTONE_TEMPLATE = """\
# Milestone: {name}

> **Target Date**: {target_date}
> **Status**: {status}
> **Sprints**: {sprints}

## Goal
{goal}

## Features
- [ ] (Add features here)
"""


def create_milestone(studio_path: Path, slug: str, name: str, target_date: str,
                     goal: str, sprints: list[int], status: str = "Planned") -> Path:
    p = _milestone_path(studio_path, slug)
    p.parent.mkdir(parents=True, exist_ok=True)
    sprint_str = ", ".join(str(n) for n in sprints) if sprints else ""
    p.write_text(
        _MILESTONE_TEMPLATE.format(
            name=name, target_date=target_date, status=status,
            sprints=sprint_str, goal=goal,
        ),
        encoding='utf-8',
    )
    return p


def update_milestone(studio_path: Path, slug: str, name: str, target_date: str,
                     goal: str, sprints: list[int], status: str) -> bool:
    p = _milestone_path(studio_path, slug)
    if not p.exists():
        return False
    content = p.read_text(encoding='utf-8')
    sprint_str = ", ".join(str(n) for n in sprints) if sprints else ""

    content = re.sub(r'\*{0,2}Target Date\*{0,2}[:\s]+[^\n]+',
                     f'**Target Date**: {target_date}', content)
    content = re.sub(r'\*{0,2}Status\*{0,2}[:\s]+[^\n]+',
                     f'**Status**: {status}', content)
    content = re.sub(r'\*{0,2}Sprints\*{0,2}[:\s]+[^\n]+',
                     f'**Sprints**: {sprint_str}', content)

    # Update H1 name
    content = re.sub(
        r'^#\s+(?:Milestone:\s*)?.*$',
        f'# Milestone: {name}',
        content, flags=re.MULTILINE, count=1,
    )

    # Update goal section
    content = re.sub(
        r'(## Goal\s*\n).*?(?=\n## |\Z)',
        f'\\g<1>{goal}\n\n',
        content, flags=re.DOTALL, count=1,
    )

    p.write_text(content, encoding='utf-8')
    return True


def delete_milestone(studio_path: Path, slug: str) -> bool:
    p = _milestone_path(studio_path, slug)
    if p.exists():
        p.unlink()
        return True
    return False
